title: Dylan Karkainen
description: AOS C111/204 Final Project
<img align="right" width="220" height="220" src="/assets/IMG/new_mine.png">
logo: /assets/IMG/new_mine.png
show_downloads: true
theme: jekyll-theme-hacker
